### ISSUE TITLE
[메뉴]사용자는 출력된 커피 메뉴를 확인 할 수 있습니다.

### ISSUE THREAD

**Issue by yejinlee99** [pladata-encore/DA36-mini1-seotarbucks#1]
## 🌈 Success criteria

1. 사용자는 메인 메뉴에서 커피 주문을 선택하고, 커피 메뉴를 모두 선택 할 수 있습니다.
2. 메뉴에는 메뉴 이름과 가격을 확인할 수 있어야 합니다.
3. 사용자가 메뉴를 선택하면 Hot/Cold 선택 창이 나옵니다.
4. Hot/Cold 선택 후 수량, 사이즈, 얼음양, 당도 를 물어보는 옵션 창들이 나와야 합니다.
5. 모든 입력이 완료되면, 메뉴 선택을 계속 할지 물어보면 좋겠습니다.

## 👷 To-do

- [ ] 메뉴 클래스 작성
- [ ] 메뉴 선정 및 메뉴 노출 구조 만들기
- [ ] 옵션 메소드 작성
- [ ] 옵션 선택 및 옵션 노출 구조 만들기
- [ ] 메뉴 선택 내역 노출하기
- [ ] 메뉴 선택 계속할지 여부 물어보는 메세지 노출하기

## 🧶 Review

![image](https://github.com/user-attachments/assets/1ee9768c-8dd1-4da4-900f-7d8c40011c34)
![image](https://github.com/user-attachments/assets/e069e11d-8b7a-4017-b50a-ce591ba05f77)
![image](https://github.com/user-attachments/assets/7ec28bc5-848d-41dd-a8d6-85bfdc1db942)
![image](https://github.com/user-attachments/assets/8c27f322-ea88-4e1b-a92b-9c08a56f755d)
![image](https://github.com/user-attachments/assets/28292726-f6a4-4280-b0cc-c4b4e0e4e4e0)
![image](https://github.com/user-attachments/assets/ba350f23-b8c8-470d-b273-2eb682884c61)
