### ISSUE TITLE
[메뉴]사용자는 출력된 논-커피 메뉴를 확인 할 수 있습니다.

### ISSUE THREAD

**Issue by yejinlee99** [pladata-encore/DA36-mini1-seotarbucks#23]
## 🌈 Success criteria

1. 사용자는 메인 메뉴에서 논-커피 주문을 선택하고, 논-커피 메뉴를 모두 선택 할 수 있습니다.
2. 메뉴에는 메뉴 이름과 가격을 확인할 수 있어야 합니다.
3. 사용자가 메뉴를 선택하면 Hot/Cold 선택 창이 나옵니다.
4. Hot/Cold 선택 후 수량, 사이즈, 얼음양, 당도 를 물어보는 옵션 창들이 나와야 합니다.
5. 모든 입력이 완료되면, 메뉴 선택을 계속 할지 물어보면 좋겠습니다.

## 👷 To-do

- [ ]  메뉴 클래스 작성
- [ ] 메뉴 선정 및 메뉴 노출 구조 만들기
- [ ] 옵션 메소드 작성
- [ ] 옵션 선택 및 옵션 노출 구조 만들기
- [ ] 메뉴 선택 내역 노출하기
- [ ] 메뉴 선택 계속할지 여부 물어보는 메세지 노출하기

## 🧶 Review

![image](https://github.com/user-attachments/assets/d5ce0d43-3e99-4395-bf2f-6005c56335e5)
![image](https://github.com/user-attachments/assets/42731c12-4903-4def-927e-697b5915a756)
![image](https://github.com/user-attachments/assets/47779e50-06cf-4b34-adf3-775b1f12af98)
![image](https://github.com/user-attachments/assets/af956209-86af-472f-afe8-d57555cf8fea)
![image](https://github.com/user-attachments/assets/53b5c06f-4ea4-4a0c-bf3f-9e94f85010e3)
![image](https://github.com/user-attachments/assets/64852c7b-8866-4205-959b-3d005888eef6)
