### ISSUE TITLE
[메뉴]사용자는 출력된 블렌디드 메뉴를 확인 할 수 있습니다. 

### ISSUE THREAD

**Issue by yejinlee99** [pladata-encore/DA36-mini1-seotarbucks#24]
## 🌈 Success criteria

1.사용자는 메인 메뉴에서 블렌디드 주문을 선택하고, 블렌디드 메뉴를 모두 선택 할 수 있습니다.
2. 메뉴에는 메뉴 이름과 가격을 확인할 수 있어야 합니다.
3. 사용자가 메뉴를 선택하면 수량, 사이즈, 얼음양, 당도 를 물어보는 옵션 창들이 나와야 합니다.
**블렌디드는 only ice 이므로 Hot/Cold 선택 창이 안나와도 된다.**
4. 모든 입력이 완료되면, 메뉴 선택을 계속 할지 물어보면 좋겠습니다.

## 👷 To-do

- [ ]  메뉴 클래스 작성
- [ ] 메뉴 선정 및 메뉴 노출 구조 만들기
- [ ] 옵션 메소드 작성
- [ ] 옵션 선택 및 옵션 노출 구조 만들기
- [ ] 메뉴 선택 내역 노출하기
- [ ] 메뉴 선택 계속할지 여부 물어보는 메세지 노출하기

## 🧶 Review

![image](https://github.com/user-attachments/assets/9ee3f035-491f-4a92-8698-e6d17ea1bbbf)
![image](https://github.com/user-attachments/assets/ed973833-8465-4517-9ec2-1363d209c042)
![image](https://github.com/user-attachments/assets/5b4edc84-c314-42c3-bb48-876540d3fcfa)
![image](https://github.com/user-attachments/assets/87a073af-5373-4469-a6e7-a9959fc3d6dc)
![image](https://github.com/user-attachments/assets/36739507-2b7f-43e3-b4eb-0f4974390c5a)
