### ISSUE TITLE
[결제]사용자는 선택한 메뉴를 결제할 수 있습니다.

### ISSUE THREAD

**Issue by yejinlee99** [pladata-encore/DA36-mini1-seotarbucks#26]
## 🌈 Success criteria

1. 사용자는 결제 화면에서 통신사 할인을 선택 할 수 있습니다.
2. 통신사 할인 선택 목록에는 통신사 이름과 할인율을 확인할 수 있어야 합니다.
3. 사용자가 통신사 할인을 선택하면 할인이 적용된 가격이 나오는 주문 내역 확인 창이 나와야 합니다.
4. 확인 이 완료되면 멤버쉽이 있는지 물어봐야 합니다.
5. 멤버쉽이 없다면 회원가입을 할건지 물어봐야 합니다.
6. 회원가입은 핸드폰 번호로 해야하고 적립을 해줘야 합니다.
7. 적립 후 결제 수단을 물어봐야합니다.
8. 결제가 완료되면 키오스크가 종료됩니다.

## 👷 To-do

- [ ]  결제 클래스 작성
- [ ] 통신사 할인 메뉴 및 통신사 할인 노출 구조 만들기
- [ ] 통신사 할인이 적용된 가격이 노출되는 구조 만들기
- [ ] 멤버쉽 메소드 작성 및 노출 구조 만들기
- [ ] 적립 내역 노출 구조 만들기
- [ ] 결제수단 메소드 작성
- [ ] 결제 수단 선택 후 매출 내역 저장하고 종료 시키기

## 🧶 Review

![image](https://github.com/user-attachments/assets/f3e58c3b-d399-40e3-900a-83ed9c502bc3)
![image](https://github.com/user-attachments/assets/23594487-36b1-4272-b958-1f3b5f5cf153)
![image](https://github.com/user-attachments/assets/8a14a601-020d-4689-80b0-140ae4c68da8)
![image](https://github.com/user-attachments/assets/7aab37aa-54f5-404a-8d6a-649addec2c91)
![image](https://github.com/user-attachments/assets/44f94a31-e1a1-4eb9-b959-f83f5f7dd48f)
![image](https://github.com/user-attachments/assets/6296eee6-2084-45ee-844a-ffe81a952328)
