### ISSUE TITLE
[관리자] 관리자는 매출 정보를 볼 수 있습니다.

### ISSUE THREAD

**Issue by yejinlee99** [pladata-encore/DA36-mini1-seotarbucks#27]
## 🌈 Success criteria

1. 관리자는 카테고리에서 [특별한 키]를 입력 시 관리자 모드로 바꿀 수 있습니다.
2. 관리자 모드에 들어가기 위해서는 비밀번호를 입력해야 합니다.
3. 비밀번호가 맞을 시 매출 정보에 관한 내용을 볼 수 있습니다.
4. 관리자 모드에서 매출 정보 조회,  엑셀로 만들기, sort, 통계 를 할 수 있습니다.

## 👷 To-do

- [ ] 관리자 클래스 작성
- [ ] 관리자 메뉴 및 관리자 화면 노출 구조 만들기
- [ ] 매출 정보 조회 메소드 작성
- [ ] 엑셀로 만들기 메소드 작성
- [ ] sort 하는 메소드 작성
- [ ] 통계 하는 메소드 작성
- [ ] 결과 노출 구조 만들기

## 🧶 Review

![image](https://github.com/user-attachments/assets/15773ab5-19a8-4b8a-bd4c-826ec523d4ab)
![image](https://github.com/user-attachments/assets/367f43c6-043e-48b0-87f4-41a498d8cd8c)
![image](https://github.com/user-attachments/assets/7d993963-0e3f-4b24-ab75-ebb39294317d)
![image](https://github.com/user-attachments/assets/00e3eca0-172e-4312-b8fc-ce17c89bb286)
![image](https://github.com/user-attachments/assets/5bb62965-173a-4b66-8e3d-1dd65be646fa)
![image](https://github.com/user-attachments/assets/1b89d115-2984-47aa-bef3-bc57305ebe08)
![image](https://github.com/user-attachments/assets/939d167d-a738-4736-9590-caf2b724bf36)
![image](https://github.com/user-attachments/assets/0a7a1438-2408-4d0e-a486-ca94baa20fba)
![image](https://github.com/user-attachments/assets/0137ffea-3fb6-46bc-95ad-9c302e852372)
