### ISSUE TITLE
전체적인 흐름 워드로 작성하기

### ISSUE THREAD

**Issue by yejinlee99** [pladata-encore/DA36-mini1-seotarbucks#9]
## 🌈 Success criteria

1. 전체적인 흐름을 워드로 작성 후 구글 공유 문서함에 올려주세요.

## 👷 To-do

- [ ]  메뉴를 선택하면 커피, 논카페인, 블렌디드, 종료 카테고리가 나오게 해주세요.
- [ ] 종료를 누르면 이전 단계로 돌아가게 해주세요.
- [ ] -1를 누르면 관리자 창이 실행되게 해주세요.
- [ ] 카테고리가 선택되면 어떤 옵션이 나오는지 카테고리 별로 작성해 주세요.(1-1 HOT/ICED, 1-2 사이즈, ...) 
- [ ] 카테고리 작성 후 장바구니로 들어가게 해주세요.
- [ ] 장바구니가 모였다면 결제창으로 넘어가게 해주세요.
- [ ] 결제창에서 어떤 옵션들(할인여부,...)을 보여줄지 작성해 주세요.
- [ ] 할인된 금액을 보여주는 창을 만들어 주세요.
- [ ] 최종 결제 금액이 나오는 창을 만들어 주세요.(a.k.a 영수증)
- [ ] 관리자 창에서 어떤 옵션들이 나오는지 작성해 주세요.(매출 정보 조회, 매출 정보 엑셀로 내보내기, 종료)
- [ ] 각 옵션들은 선택했을 때 어떤 내용이 나왔으면 좋겠는지 작성해 주세요.
